baseURL = 'https://nekobox.info/'
languageCode = 'en-us'
title = 'nekobox'
theme='hugo-book'

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[languages]
[languages.zh]
  languageName = '中文'
  contentDir = 'content.zh'
  weight = 1

[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  weight = 3

[languages.ru]
  languageName = 'Русский'
  contentDir = 'content.ru'
  weight = 2

[languages.fa]
  languageName = 'فارسی'
  contentDir = 'content.ru'
  weight = 2



[menu]
# [[menu.before]]
[[menu.after]]
  name = "15元1000G不限时机场"
  url = "https://xn--mes995ajya725k.xyz/#/register?code=xFHkxqZv"
  weight = 20

[params]
# 黑暗模式
  BookTheme = 'dark'
# 留言板
  BookComments = true
# 翻译
  BookTranslatedOnly = true



